@extends('investigation.layouts.app')

@section('title', 'All Incident Records')

@push('styles')
<link rel="stylesheet" href="{{ asset('css/investigation/incidents.css') }}">
@endpush

@section('content')

<div class="d-flex align-items-center gap-2 mb-2">
    <h6 class="fw-bold mb-0" style="color:#111827;">Saved Incident Record Forms</h6>
    <span class="badge rounded-pill" style="background:#1b3d52; font-size:.72rem;">
        {{ ($records ?? collect())->count() }}
    </span>
</div>
<p class="text-muted mb-3" style="font-size:.85rem;">
    Every Incident Record Form ever saved, including walk-in reports not
    linked to any incident in the system. Click a row to reopen it.
</p>

{{-- FILTER BAR --}}
<div class="d-flex align-items-center gap-2 mb-4 flex-wrap">
    <div class="input-group flex-grow-1" style="min-width:200px;">
        <span class="input-group-text bg-white" style="border-color:#c8d8e4;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="none"
                 stroke="#6b7280" stroke-width="2" stroke-linecap="round"
                 stroke-linejoin="round" viewBox="0 0 24 24">
                <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
            </svg>
        </span>
        <input type="text" id="searchInput" class="form-control"
               placeholder="Search Incident Records..."
               style="border-color:#c8d8e4;">
    </div>

    <select class="form-select" id="statusFilter" style="max-width:180px; border-color:#c8d8e4;">
        <option value="">All Status</option>
        <option value="Saved">Saved only</option>
        <option value="Printed">Saved &amp; Printed</option>
    </select>
</div>

<div class="card border rounded-3" style="border-color:#d1dde6 !important;">
    <div class="table-responsive">
        <table class="incidents-table w-100" id="recordsTable">
            <thead>
                <tr>
                    <th>Date/Time</th>
                    <th>Linked Incident</th>
                    <th>Status</th>
                    <th>Generated By</th>
                </tr>
            </thead>
            <tbody id="recordsBody">
                @forelse($records ?? [] as $record)
                @php
                    $uiStatus = $record->printed_at ? 'Printed' : 'Saved';
                @endphp
                <tr data-status="{{ $uiStatus }}"
                    onclick="window.location='{{ route('investigation.incident-records.reprint', $record) }}'"
                    style="cursor:pointer;">
                    <td><span class="incident-time">{{ $record->created_at->format('M d, Y h:i A') }}</span></td>
                    <td>
                        @if($record->incident)
                            #{{ $record->incident->id }} — {{ ucfirst($record->incident->type) }}
                            ({{ $record->incident->rider?->full_name ?? 'Unknown rider' }})
                        @else
                            <span class="status-badge" style="border-color:#9ca3af; color:#6b7280; font-size:.72rem;">Not linked</span>
                        @endif
                    </td>
                    <td>
                        <span class="status-badge {{ $record->printed_at ? 'status-resolved' : 'status-active' }}">
                            {{ $record->printed_at ? 'Saved & Printed' : 'Saved' }}
                        </span>
                    </td>
                    <td>{{ $record->generatedBy?->full_name ?? 'Unknown officer' }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="4" class="text-center text-muted py-5">
                        <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="none"
                             stroke="#c8d8e4" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"
                             viewBox="0 0 24 24" class="mb-2 d-block mx-auto">
                            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                            <polyline points="14 2 14 8 20 8"/>
                        </svg>
                        <span style="font-size:.83rem;">No Incident Record Forms have been saved yet.</span>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>

@endsection

@push('scripts')
<script>
    function filterTable() {
        const search = document.getElementById('searchInput').value.toLowerCase();
        const status = document.getElementById('statusFilter').value;

        document.querySelectorAll('#recordsBody tr').forEach(row => {
            const text      = row.textContent.toLowerCase();
            const rowStatus = row.dataset.status ?? '';

            const matchSearch = text.includes(search);
            const matchStatus = !status || rowStatus === status;

            row.style.display = (matchSearch && matchStatus) ? '' : 'none';
        });
    }

    document.getElementById('searchInput').addEventListener('input', filterTable);
    document.getElementById('statusFilter').addEventListener('change', filterTable);
</script>
@endpush
